### ISSUE TITLE
Idea: Graphics for Ioniq 6

### ISSUE THREAD

**Issue by julianjwong** [rchiileea/ioniq5-and-ioniq6-dashboard-for-ha#1]
Hey thanks for sharing your custom integration for the Ioniq 5. I've installed and configured it fory Ioniq 6 and it works for everything apart from the Odometer which seems to be missing from the Hyundai bluelink integration. How did you go about creating the graphics for the Ioniq 5? I'd like to see if this is possible for the Ioniq 6 but not really sure how to best start.

**Comment by rchiileea** [comment]
Sorry about delay in response never got the notification @julianjwong updating soon with ioniq 6 pictures

**Comment by julianjwong** [comment]
Awesome thanks! Unfortunately my Hyundai integration stopped working for some reason. Tried removing and redoing but some error. Haven't bothered debugging yet but will take a look.

Edit:
Looks like the Hyundai integration had an authentication error despite my password being correct. Did a password reset and all good again. Will keep a lookout for your Ioniq 6 images

**Comment by julianjwong** [comment]
Hey mate thanks for the updates to add the graphics. Managed to add them in and seems to be all good!
